# Generated by Django 4.1.7 on 2023-02-28 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0003_author_password_post_slug_alter_post_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_text', to='techapp.post'),
        ),
    ]
