# Generated by Django 4.1.7 on 2023-02-28 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0004_remove_post_comment_text_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_text', to='techapp.post'),
        ),
    ]
